name: Build & Publish

on:
  pull_request:
    branches:
      - 'main'

jobs:
 build_apk_aab:
   if: startsWith(github.head_ref, 'release/') == true
   name: Build release artifacts
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: |
          ./gradlew test
          ./gradlew assembleDebug --stacktrace
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            tag_name: ${{ env.VERSION_TAG }}
            name: Release ${{ env.VERSION_TAG }}
            body: |
              ---
              ### Checksums
              | Variant | SHA-256 |
              | ------- | ------- |
              | Universal | ${{ env.APK_UNIVERSAL_SHA }}
              | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
              | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
              | x86 | ${{ env.APK_X86_SHA }} |
            files: |
              app/build/outputs/apk/release/app-release.apk
              app/build/outputs/apk/debug/app-debug.apk
            draft: false
            prerelease: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
