# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew testDebugUnitTest
      - name: Generate apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/debug/app-debug.apk

      - name: Upload signed apk
        id: signArtifact
        uses: r0adkll/sign-android-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
            releaseDirectory: app/build/outputs/apk/release
            alias: ${{ secrets.KEYNAME }}
            signingKeyBase64: ${{ secrets.KEY }}
            keyStorePassword: ${{ secrets.STOREPASSWORD }}
            keyPassword: ${{ secrets.KEYPASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: app/build/outputs/apk/release/app-artifact-*.apk