name: Build & Publish

on:
  pull_request:
    branches:
      - 'main'

jobs:
 build_apk_aab:
   if: startsWith(github.head_ref, 'release/') == true
   name: Build release artifacts
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: |
          ./gradlew test
          ./gradlew assembleDebug --stacktrace
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: /home/runner/work/
          APP_FOLDER: app
          RELEASE_TITLE: New Build
        run: |
          export TAG_NAME=${{ github.ref }}
          go get -u github.com/tcnksm/ghr
          $GOPATH/bin/ghr -n $TAG_NAME "${TAG_NAME##*/}" "${GITHUB_WORKSPACE}/app/build/outputs/apk/release/app-release.apk"
          $GOPATH/bin/ghr -n $TAG_NAME "${TAG_NAME##*/}" "${GITHUB_WORKSP¥ACE}/app/build/outputs/bundle/release/app-release.aab"
          $GOPATH/bin/ghr -n $TAG_NAME "${TAG_NAME##*/}" "${GITHUB_WORKSPACE}/app/build/outputs/apk/debug/app-debug.apk"
