name: Build & Publish

on:
  pull_request:
    branches:
      - 'main'

jobs:
 build_apk_aab:
   if: startsWith(github.head_ref, 'release/') == true
   name: Build release artifacts
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: |
          ./gradlew test
          ./gradlew assembleDebug --stacktrace
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            path: |
              app/build/outputs/apk/release/app-release.apk
              app/build/outputs/apk/debug/app-debug.apk
