name: Build

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build_apk_aab:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: |
          ./gradlew test